### ISSUE TITLE
2022/08 最新版に更新

### ISSUE THREAD

**Issue by otanikohei** [jaws-ug/JAWSUG_Map#8]
## 最新版に更新

[勉強会グループ一覧](https://jaws-ug.jp/act/) に沿って、支部の情報を更新が必要です。

### 削除対象
- 目黒支部
- 長岡支部
- 白山支部
- 湘南支部
- つくば支部
- 福井支部
- 和歌山支部
- 中央線東海支部
- X-Tech JAWS
- iJAWS
- 山口支部
- 北九州市部
- 宮崎支部
- シンガポール
- 静岡支部

### 追加対象
- JAWS-UG 朝会
- JAWS-UG GameTech 専門支部
- JAWS-UG関西（ALL）
- AI/ML 支部

### 例外
- 一覧にはありませんが、E-JAWSを追加すべきと考えます。

## 支部数の修正
- 全部で 64 支部のため、70+ を 60+ に変更が必要です。

## ファイルフォーマット
Adobe Illustrator の ai ファイルがベースとなっており、編集者が限定されることから Powerpoint ファイルを編集可能なオブジェクトに変更する方針を提案させていただきます。

## 英語版
英語版の作成したいというご意見があったため提案させていただきます。

| No | 日本語 | 英語 |
| --- | --- | --- |
|1|札幌支部|Sapporo|
|2|函館支部|Hakodate|
|3|青森支部|Aomori|
|4|秋田支部|Akita|
|5|仙台支部|Sendai|
|6|山形支部|Yamagata|
|7|会津支部|Aidzu|
|8|東京支部|Tokyo|
|9|六本木一丁目|Roppongi|
|10|横浜支部|Yokohama|
|11|千葉支部|Chiba|
|12|さいたま支部|Saitama|
|13|群馬支部|Gunma|
|14|金沢支部|Kanazawa|
|15|新潟支部|Niigata|
|16|上越妙高支部|Joetsu Myoko|
|17|浜松支部|Hamamatsu|
|18|磐田支部|Iwata|
|19|岐阜支部|Gifu|
|20|長野支部|Nagano|
|21|名古屋支部|Nagoya|
|22|大阪支部|Osaka|
|23|JAWS-UG関西(ALL)|Kansai ALL|
|24|神戸支部|Kobe|
|25|京都支部、関西IoT|Kyoto|
|26|関西女子会|Kansai Girls|
|27|関西IoT|Kansai IoT|
|28|岡山支部|Okayama|
|29|島根支部|Shimane|
|30|広島支部|Hiroshima|
|31|徳島支部|Tokushima|
|32|愛媛支部|Ehime|
|33|高知支部|Kochi|
|34|香川支部|Kagawa|
|35|福岡支部|Fukuoka|
|36|熊本支部|Kumamoto|
|37|大分支部|Oita|
|38|鹿児島支部|Kagoshima|
|39|佐賀支部|Saga|
|40|長崎支部|Nagasaki|
|41|沖縄支部|Okinawa|
|42|中央線支部|Chuo Line|
|43|京王線支部|Keio|
|44|クラウド女子会|Cloud Girls|
|45|初心者支部|Beginner|
|46|CLI専門支部|CLI|
|47|コンテナ支部|Container|
|48|HPC|HPC|
|49|E-JAWS|Enterprise (E-JAWS)|
|50|Fin-JAWS|Finance (Fin-JAWS)|
|51|Ops JAWS|Operations (Ops-JAWS)|
|52|アーキテクチャ専門支部|Architecture|
|53|JAWS-UG情シス|JAWS-UG Systems Admin|
|54|IoT専門支部|IoT|
|55|NW-JAWS|Network (NW-JAWS)|
|56|Security-JAWS|Security (Security-JAWS)|
|57|ビッグデータ支部|Bigdata (Bigdata-JAWS)|
|58|AI/ML支部|AI/ML|
|59|Media-JAWS|Media|
|60|JAWS-UG Sales|Sales|
|61|JAWS-UG朝会|Morning Meeting|
|62|SRE支部|SRE|
|63|CDK支部|CDK|
|64|GameTech|GameTech|

**Comment by otanikohei** [comment]
最新版がありますので、プルリクをお送りします。

**Comment by otanikohei** [comment]
更新しました。

- 追加
  - Storage-JAWS
  - 静岡 のないバージョン
- 変更
  - 関西クラウド女子会→JAWS-UG DE&I
- 削除
  - 鹿児島支部 （編集済み

**Comment by otanikohei** [comment]
新しく Issue を立てました。よろしくお願いします。

**Comment by matyuda** [comment]
ありがとうございます。
本件クローズします。
